define %struct.SEXPREC addrspace(1)* @rfunction(%struct.SEXPREC addrspace(1)* %consts, %struct.SEXPREC addrspace(1)* %rho, i32 %useCache) #0 gc "rjit" {
start:
  %safepoint_token = tail call i32 (i64, i32, %struct.SEXPREC addrspace(1)* (%struct.SEXPREC addrspace(1)*, %struct.SEXPREC addrspace(1)*, i32)*, i32, i32, ...) @llvm.experimental.gc.statepoint.p0f_p1struct.SEXPRECp1struct.SEXPRECp1struct.SEXPRECi32f(i64 4, i32 0, %struct.SEXPREC addrspace(1)* (%struct.SEXPREC addrspace(1)*, %struct.SEXPREC addrspace(1)*, i32)* @genericGetVar, i32 3, i32 0, %struct.SEXPREC addrspace(1)* %rho, %struct.SEXPREC addrspace(1)* %consts, i32 1, i32 0, i32 2, %struct.SEXPREC addrspace(1)* %consts, %struct.SEXPREC addrspace(1)* %rho)
  %a.1 = call %struct.SEXPREC addrspace(1)* @llvm.experimental.gc.result.p1struct.SEXPREC(i32 %safepoint_token)
  %safepoint_token.2 = tail call i32 (i64, i32, %struct.SEXPREC addrspace(1)* (%struct.SEXPREC addrspace(1)*, i32)*, i32, i32, ...) @llvm.experimental.gc.statepoint.p0f_p1struct.SEXPRECp1struct.SEXPRECi32f(i64 5, i32 0, %struct.SEXPREC addrspace(1)* (%struct.SEXPREC addrspace(1)*, i32)* @userLiteral, i32 2, i32 0, %struct.SEXPREC addrspace(1)* %consts, i32 2, i32 0, i32 3, %struct.SEXPREC addrspace(1)* %a.1, %struct.SEXPREC addrspace(1)* %consts, %struct.SEXPREC addrspace(1)* %rho)
  %0 = call %struct.SEXPREC addrspace(1)* @llvm.experimental.gc.result.p1struct.SEXPREC(i32 %safepoint_token.2)
  %safepoint_token.3 = tail call i32 (i64, i32, %struct.SEXPREC addrspace(1)* (%struct.SEXPREC addrspace(1)*, %struct.SEXPREC addrspace(1)*, %struct.SEXPREC addrspace(1)*, %struct.SEXPREC addrspace(1)*, i32)*, i32, i32, ...) @llvm.experimental.gc.statepoint.p0f_p1struct.SEXPRECp1struct.SEXPRECp1struct.SEXPRECp1struct.SEXPRECp1struct.SEXPRECi32f(i64 6, i32 0, %struct.SEXPREC addrspace(1)* (%struct.SEXPREC addrspace(1)*, %struct.SEXPREC addrspace(1)*, %struct.SEXPREC addrspace(1)*, %struct.SEXPREC addrspace(1)*, i32)* @genericAdd, i32 5, i32 0, %struct.SEXPREC addrspace(1)* %a.1, %struct.SEXPREC addrspace(1)* %0, %struct.SEXPREC addrspace(1)* %rho, %struct.SEXPREC addrspace(1)* %consts, i32 0, i32 0, i32 4, %struct.SEXPREC addrspace(1)* %0, %struct.SEXPREC addrspace(1)* %a.1, %struct.SEXPREC addrspace(1)* %consts, %struct.SEXPREC addrspace(1)* %rho)
  %1 = call %struct.SEXPREC addrspace(1)* @llvm.experimental.gc.result.p1struct.SEXPREC(i32 %safepoint_token.3)
  ret %struct.SEXPREC addrspace(1)* %1, !r_ir_type !0
}